import {test, expect} from '@playwright/test';
import {env} from 'node:process';
import {apiHeaders, login, randomString} from './utils.ts';

test('原生审批草稿、原子保存、版本冲突及窄屏', async ({page, request}, info) => {
  const repo = `approval-draft-${randomString(8)}`;
  const owner = env.GITEA_TEST_E2E_USER;
  const headers = apiHeaders();
  const created = await request.post('/api/v1/user/repos', {headers, data: {name: repo, auto_init: true}});
  expect(created.status()).toBe(201);
  const endpoint = `/api/v1/repos/${owner}/${repo}/branch_protections`;
  const protection = await request.post(endpoint, {headers, data: {rule_name: 'main', enable_push: false}});
  expect(protection.status()).toBe(201);
  const initial = await protection.json();
  const path = `/${owner}/${repo}/settings/branches/edit?rule_id=${initial.approval_configuration.protection_id}`;
  const errors: string[] = [];
  page.on('pageerror', (error) => { errors.push(error.message) });
  await login(page);
  await page.goto(path);
  const draft = async (name: string) => {
    await page.locator('[data-approval-add]').click();
    await page.locator('[data-rule-name]').fill(name);
    await page.locator('[data-rule-required]').fill('0');
    await page.locator('[data-rule-all]').check();
    await page.locator('[data-rule-apply]').click();
    await expect(page.locator('[data-approval-rows]')).toContainText(name);
  };
  const readRules = async () => {
    const response = await request.get(`${endpoint}/main`, {headers});
    expect(response.status()).toBe(200);
    return (await response.json()).approval_configuration.rules;
  };
  await draft('取消后不落盘');
  expect((await readRules()).some((r: {name: string}) => r.name === '取消后不落盘')).toBe(false);
  page.once('dialog', (dialog) => dialog.accept());
  await page.reload();
  await expect(page.locator('[data-approval-rows]')).not.toContainText('取消后不落盘');
  await draft('已保存的可选规则');
  await Promise.all([page.waitForURL(`**/${owner}/${repo}/settings/branches`), page.getByRole('button', {name: '保存分支保护', exact: true}).click()]);
  expect((await readRules()).some((r: {name: string}) => r.name === '已保存的可选规则')).toBe(true);
  await page.goto(path);
  await draft('发生冲突仍保留');
  const external = await request.patch(`${endpoint}/main`, {headers, data: {required_approvals: 1}});
  expect(external.status()).toBe(200);
  const failed = page.waitForResponse((response) => response.request().method() === 'POST' && response.url().includes('/settings/branches/edit'));
  await page.getByRole('button', {name: '保存分支保护', exact: true}).click();
  expect((await failed).status()).toBe(409);
  await expect(page.locator('[data-approval-error]')).toBeVisible();
  await expect(page.locator('[data-approval-rows]')).toContainText('发生冲突仍保留');
  expect((await readRules()).some((r: {name: string}) => r.name === '发生冲突仍保留')).toBe(false);
  await page.setViewportSize({width: 390, height: 844});
  await page.emulateMedia({colorScheme: 'dark'});
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await page.locator('[data-approval-add]').click();
  await expect(page.locator('[data-rule-name]')).toBeFocused();
  const box = await page.locator('[data-approval-dialog]').boundingBox();
  expect(box!.x).toBeGreaterThanOrEqual(0);
  expect(box!.x + box!.width).toBeLessThanOrEqual(390);
  await page.screenshot({path: info.outputPath('branch-narrow-dark.png'), fullPage: false});
  await page.keyboard.press('Escape');
  await expect(page.locator('[data-approval-dialog]')).toBeHidden();
  expect(errors).toEqual([]);
});
