// Copyright 2021 The Gitea Authors. All rights reserved.
// SPDX-License-Identifier: MIT

package asymkey

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"sync"

	"gitea.dev/models/db"
	"gitea.dev/modules/log"
	"gitea.dev/modules/setting"
	"gitea.dev/modules/util"

	"golang.org/x/crypto/ssh"
)

// AuthorizedStringCommentPrefix is a magic tag
// some functions like RegeneratePublicKeys needs this tag to skip the keys generated by Gitea, while keep other keys
const AuthorizedStringCommentPrefix = `# gitea public key`

var sshOpLocker sync.Mutex

func WithSSHOpLocker(f func() error) error {
	sshOpLocker.Lock()
	defer sshOpLocker.Unlock()
	return f()
}

// AuthorizedStringForKey creates the authorized keys string appropriate for the provided key
func AuthorizedStringForKey(key *PublicKey) (string, error) {
	sb := &strings.Builder{}
	_, err := writeAuthorizedStringForKey(key, sb)
	return sb.String(), err
}

// WriteAuthorizedStringForValidKey writes the authorized key for the provided key. If the key is invalid, it does nothing.
func WriteAuthorizedStringForValidKey(key *PublicKey, w io.Writer) error {
	validKey, err := writeAuthorizedStringForKey(key, w)
	if !validKey {
		log.Debug("WriteAuthorizedStringForValidKey: key %s is not valid: %v", key, err)
		return nil
	}
	return err
}

var globalVars = sync.OnceValue(func() (ret struct {
	principalRegexp *regexp.Regexp
},
) {
	// principalRegexp expresses whether a principal is considered valid.
	// This reverse engineers how sshd parses the authorized keys file,
	// see e.g. https://github.com/openssh/openssh-portable/blob/32deb00b38b4ee2b3302f261ea1e68c04e020a08/auth2-pubkeyfile.c#L221-L256
	// Any newline or # comment will be stripped when parsing, so don't allow
	// those. Also, if any space or tab is present in the principal, the part
	// proceeding this would be parsed as an option, so just avoid any whitespace
	// altogether.
	ret.principalRegexp = regexp.MustCompile(`^[^\s#]+$`)
	return ret
})

func writeAuthorizedStringForKey(key *PublicKey, w io.Writer) (keyValid bool, err error) {
	const tpl = AuthorizedStringCommentPrefix + "\n" + `command=%s,no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty,no-user-rc,restrict %s` + "\n"

	var sshKey string

	if key.Type == KeyTypePrincipal {
		// TODO: actually using PublicKey to store "principal" is an abuse
		if !globalVars().principalRegexp.MatchString(key.Content) {
			return false, fmt.Errorf("invalid principal key: %s", key.Content)
		}
		sshKey = fmt.Sprintf("%s # user-%d", key.Content, key.OwnerID)
	} else {
		pubKey, _, _, _, err := ssh.ParseAuthorizedKey([]byte(key.Content))
		if err != nil {
			return false, err
		}

		sshKeyMarshalled := strings.TrimSpace(string(ssh.MarshalAuthorizedKey(pubKey)))
		sshKey = fmt.Sprintf("%s user-%d", sshKeyMarshalled, key.OwnerID)
	}

	// now the key is valid, the code below could only return template/IO related errors
	sbCmd := &strings.Builder{}
	err = setting.SSH.AuthorizedKeysCommandTemplateTemplate.Execute(sbCmd, map[string]any{
		"AppPath":     util.ShellEscape(setting.AppPath),
		"AppWorkPath": util.ShellEscape(setting.AppWorkPath),
		"CustomConf":  util.ShellEscape(setting.CustomConf),
		"CustomPath":  util.ShellEscape(setting.CustomPath),
		"Key":         key,
	})
	if err != nil {
		return true, err
	}
	sshCommandEscaped := util.ShellEscape(sbCmd.String())
	_, err = fmt.Fprintf(w, tpl, sshCommandEscaped, sshKey)
	return true, err
}

// RegeneratePublicKeys regenerates the authorized_keys file
func RegeneratePublicKeys(ctx context.Context, t io.Writer) error {
	if err := db.GetEngine(ctx).Where("type != ?", KeyTypePrincipal).Iterate(new(PublicKey), func(idx int, bean any) (err error) {
		return WriteAuthorizedStringForValidKey(bean.(*PublicKey), t)
	}); err != nil {
		return err
	}

	fPath := filepath.Join(setting.SSH.RootPath, "authorized_keys")
	isExist, err := util.IsExist(fPath)
	if err != nil {
		log.Error("Unable to check if %s exists. Error: %v", fPath, err)
		return err
	}
	if isExist {
		f, err := os.Open(fPath)
		if err != nil {
			return err
		}
		defer f.Close()

		scanner := bufio.NewScanner(f)
		for scanner.Scan() {
			line := scanner.Text()
			if strings.HasPrefix(line, AuthorizedStringCommentPrefix) {
				scanner.Scan()
				continue
			}
			_, err = io.WriteString(t, line+"\n")
			if err != nil {
				return err
			}
		}
		if err = scanner.Err(); err != nil {
			return fmt.Errorf("RegeneratePublicKeys scan: %w", err)
		}
	}
	return nil
}
